import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import { Toaster } from "react-hot-toast";
import QueryProvider from "@/components/QueryProvider";
import { SessionProvider } from "next-auth/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || "https://bizflow.app"),
  title: "BizFlow — Business Management Suite",
  description:
    "Complete business management solution for small and medium businesses. Track inventory, sales, customers, employees and generate insightful GST reports.",
  keywords: "business management, inventory, sales, CRM, billing, GST, kirana store, India SMB",
  authors: [{ name: "BizFlow" }],
  openGraph: {
    type: "website",
    siteName: "BizFlow",
    title: "BizFlow — Business Management Suite",
    description:
      "The all-in-one platform for kirana stores, FMCG shops, fertilizer dealers, and hardware businesses. Manage inventory, sales, employees and GST billing.",
    locale: "en_IN",
    // OG image auto-generated by src/app/opengraph-image.tsx (Next.js convention)
  },
  twitter: {
    card: "summary_large_image",
    title: "BizFlow — Business Management Suite",
    description:
      "All-in-one business management for Indian SMBs. Inventory · Sales · GST Billing · Employee Management.",
  },
  icons: {
    icon: "/icon.svg",
    shortcut: "/icon.svg",
    apple: "/icon.svg",
  },
  robots: {
    index: false,
    follow: false,
    googleBot: { index: false, follow: false },
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // M-N6 FIX: userScalable must be true — required for WCAG 2.1 SC 1.4.4 (Resize Text)
  userScalable: true,
  themeColor: "#0d0d1a",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Anti-FOUC: restore theme before first paint */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('bizflow-theme');if(t==='light')document.documentElement.classList.add('light');}catch(e){}})();`,
          }}
        />
      </head>
      <body className={`${inter.variable} font-sans antialiased`} suppressHydrationWarning>
        <SessionProvider>
          <QueryProvider>
            <AppProvider>
              {children}
              {/* Global toast notifications — replaces all alert() calls */}
              <Toaster
                position="bottom-right"
                toastOptions={{
                  duration: 4000,
                  style: {
                    background: "#1a1a2e",
                    color: "#e2e8f0",
                    border: "1px solid rgba(139,92,246,0.2)",
                    borderRadius: "12px",
                    fontSize: "14px",
                  },
                  success: { iconTheme: { primary: "#10b981", secondary: "#1a1a2e" } },
                  error:   { iconTheme: { primary: "#ef4444", secondary: "#1a1a2e" } },
                }}
              />
            </AppProvider>
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
